# Generated by Django 5.2.8 on 2025-11-25 22:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Avaliação')),
                ('value', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Nota')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data da Avaliação')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.enrollment', verbose_name='Matrícula')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.subject', verbose_name='Matéria')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data da Aula')),
                ('present', models.BooleanField(default=True, verbose_name='Presente')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.enrollment', verbose_name='Matrícula')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.subject', verbose_name='Matéria')),
            ],
            options={
                'verbose_name': 'Frequência',
                'verbose_name_plural': 'Frequências',
                'unique_together': {('enrollment', 'subject', 'date')},
            },
        ),
    ]
