# Generated by Django 5.2.8 on 2025-12-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Celular/WhatsApp')),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='Profissão')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name'], 'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.AddField(
            model_name='student',
            name='allergies',
            field=models.TextField(blank=True, verbose_name='Alergias'),
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(default='Mogi das Cruzes', max_length=50, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='student',
            name='complement',
            field=models.CharField(blank=True, max_length=50, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='student',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contato de Emergência (Nome/Tel)'),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=10, verbose_name='Gênero'),
        ),
        migrations.AddField(
            model_name='student',
            name='medications',
            field=models.TextField(blank=True, verbose_name='Uso Contínuo de Medicamentos'),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(default='Brasileira', max_length=50, verbose_name='Nacionalidade'),
        ),
        migrations.AddField(
            model_name='student',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='student',
            name='number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/'),
        ),
        migrations.AddField(
            model_name='student',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(default='SP', max_length=2, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='student',
            name='street',
            field=models.CharField(blank=True, max_length=150, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='student',
            name='zip_code',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome Completo'),
        ),
        migrations.AddField(
            model_name='student',
            name='guardians',
            field=models.ManyToManyField(blank=True, related_name='students', to='academic.guardian', verbose_name='Responsáveis'),
        ),
    ]
