# Generated by Django 5.2.8 on 2025-11-25 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_grade_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso'),
        ),
    ]
