# Generated by Django 5.2.8 on 2025-12-12 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_guardian_alter_student_options_student_allergies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Início da Semana')),
                ('end_date', models.DateField(verbose_name='Fim da Semana')),
                ('topic', models.CharField(max_length=200, verbose_name='Tema / Tópico Principal')),
                ('description', models.TextField(verbose_name='Desenvolvimento da Aula')),
                ('resources', models.TextField(blank=True, verbose_name='Recursos Didáticos')),
                ('homework', models.TextField(blank=True, verbose_name='Lição de Casa / Fixação')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('SUBMITTED', 'Enviado'), ('APPROVED', 'Visto da Coordenação'), ('RETURNED', 'Precisa de Ajuste')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('coordinator_note', models.TextField(blank=True, verbose_name='Feedback da Coordenação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.teacherassignment', verbose_name='Atribuição')),
            ],
            options={
                'verbose_name': 'Planejamento Semanal',
                'verbose_name_plural': 'Planejamentos Semanais',
                'ordering': ['-start_date'],
            },
        ),
    ]
