# Generated by Django 5.2.8 on 2025-12-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_lessonplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='description',
            field=models.TextField(blank=True, verbose_name='Desenvolvimento da Aula'),
        ),
    ]
