# Generated by Django 5.2.8 on 2025-12-12 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_alter_lessonplan_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='received_plans', to=settings.AUTH_USER_MODEL, verbose_name='Enviar para'),
        ),
    ]
