# Generated by Django 5.2.8 on 2025-12-12 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_lessonplan_recipients'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherassignment',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Professores'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='Professor'),
        ),
    ]
