# Generated by Django 5.2.8 on 2026-02-03 17:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_attendance_justified_absencejustification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Atividade')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Mensal')),
            ],
            options={
                'verbose_name': 'Atividade Extra',
                'verbose_name_plural': 'Atividades Extras',
            },
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='homework',
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='resources',
        ),
        migrations.AddField(
            model_name='guardian',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Secundário / Recado'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='lesson_plans/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'jpg', 'jpeg', 'png'])], verbose_name='Anexo (Atividade/Material)'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_full_time',
            field=models.BooleanField(default=False, verbose_name='Integral?'),
        ),
        migrations.AddField(
            model_name='student',
            name='meals',
            field=models.CharField(choices=[('NONE', 'Não optante'), ('LUNCH', 'Almoço'), ('SNACK', 'Lanche'), ('BOTH', 'Almoço + Lanche')], default='NONE', max_length=20, verbose_name='Plano de Refeições'),
        ),
        migrations.AddField(
            model_name='student',
            name='medical_report',
            field=models.FileField(blank=True, null=True, upload_to='students/medical/', verbose_name='Laudo Médico'),
        ),
        migrations.AddField(
            model_name='student',
            name='period',
            field=models.CharField(choices=[('MORNING', 'Manhã'), ('AFTERNOON', 'Tarde')], default='AFTERNOON', max_length=20, verbose_name='Período'),
        ),
        migrations.AddField(
            model_name='student',
            name='prescription',
            field=models.FileField(blank=True, null=True, upload_to='students/prescriptions/', verbose_name='Receita Médica'),
        ),
        migrations.AddField(
            model_name='student',
            name='extra_activities',
            field=models.ManyToManyField(blank=True, to='academic.extraactivity', verbose_name='Atividades Extras'),
        ),
        migrations.CreateModel(
            name='SchoolEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('start_time', models.DateTimeField(verbose_name='Início')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Fim')),
                ('event_type', models.CharField(choices=[('HOLIDAY', 'Feriado / Recesso'), ('SCHOOL_DAY', 'Dia Letivo Especial'), ('EXAM', 'Prova / Avaliação'), ('ASSIGNMENT', 'Entrega de Trabalho'), ('EVENT', 'Evento / Festa'), ('MEETING', 'Reunião Pedagógica')], default='EVENT', max_length=20, verbose_name='Tipo de Evento')),
                ('target_audience', models.CharField(choices=[('ALL', 'Toda a Escola (Público)'), ('TEACHERS', 'Apenas Professores/Staff'), ('CLASSROOM', 'Turma Específica')], default='ALL', max_length=20, verbose_name='Público Alvo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='academic.classroom', verbose_name='Turma')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='academic.subject', verbose_name='Matéria')),
            ],
            options={
                'verbose_name': 'Evento / Calendário',
                'verbose_name_plural': 'Calendário Escolar',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='TaughtContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data da Aula')),
                ('content', models.TextField(verbose_name='Conteúdo Trabalhado')),
                ('homework', models.TextField(blank=True, null=True, verbose_name='Lição de Casa / Tarefa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.teacherassignment', verbose_name='Atribuição')),
            ],
            options={
                'verbose_name': 'Conteúdo Ministrado',
                'verbose_name_plural': 'Conteúdos Ministrados',
                'ordering': ['-date'],
                'unique_together': {('assignment', 'date')},
            },
        ),
    ]
