# Generated by Django 5.2.8 on 2026-02-04 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_schoolevent_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado'), (0, 'Domingo')], verbose_name='Dia da Semana')),
                ('start_time', models.TimeField(verbose_name='Início')),
                ('end_time', models.TimeField(verbose_name='Fim')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.teacherassignment')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='academic.classroom')),
            ],
            options={
                'verbose_name': 'Grade Horária',
                'verbose_name_plural': 'Grades Horárias',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('classroom', 'day_of_week', 'start_time')},
            },
        ),
    ]
