# Generated by Django 5.2.8 on 2026-02-09 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_classschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Ano Letivo')),
                ('classroom_name', models.CharField(help_text='Ex: 5º Ano B ou 3ª Série EM', max_length=100, verbose_name='Turma/Série')),
                ('school_name', models.CharField(default='Lumis School', help_text='Nome da escola onde cursou', max_length=200, verbose_name='Escola')),
                ('status', models.CharField(choices=[('APPROVED', 'Aprovado'), ('RETAINED', 'Reprovado/Retido'), ('TRANSFERRED', 'Transferido'), ('DROPOUT', 'Evadido/Desistente'), ('IN_PROGRESS', 'Cursando (Atual)')], default='APPROVED', max_length=20, verbose_name='Situação Final')),
                ('final_grade', models.CharField(blank=True, help_text='Opcional', max_length=10, null=True, verbose_name='Média Final')),
                ('observation', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_history', to='academic.student')),
            ],
            options={
                'verbose_name': 'Registro de Histórico',
                'verbose_name_plural': 'Histórico Acadêmico',
                'ordering': ['-year'],
            },
        ),
    ]
