# Generated by Django 5.2.8 on 2026-02-03 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Escola')),
                ('slug', models.SlugField(help_text='Identificador único (ex: saint-thomas)', unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/', verbose_name='Logotipo')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='school_icons/', verbose_name='Ícone (Favicon/Mobile)')),
                ('primary_color', models.CharField(default='#6366f1', help_text='Ex: #3B82F6', max_length=7, verbose_name='Cor Primária (Hex)')),
                ('secondary_color', models.CharField(default='#475569', help_text='Ex: #1E293B', max_length=7, verbose_name='Cor Secundária (Hex)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de Contato')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('address', models.TextField(blank=True, verbose_name='Endereço')),
                ('website', models.URLField(blank=True, verbose_name='Site Oficial')),
            ],
            options={
                'verbose_name': 'Configuração da Escola',
                'verbose_name_plural': 'Configurações da Escola',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
            },
        ),
    ]
