# Generated by Django 5.2.8 on 2025-11-26 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data da Observação')),
                ('pontuality', models.IntegerField(default=3, verbose_name='Pontualidade (1-5)')),
                ('class_control', models.IntegerField(default=3, verbose_name='Domínio de Classe (1-5)')),
                ('planning', models.IntegerField(default=3, verbose_name='Cumprimento do Planejamento (1-5)')),
                ('student_engagement', models.IntegerField(default=3, verbose_name='Engajamento dos Alunos (1-5)')),
                ('strong_points', models.TextField(verbose_name='Pontos Fortes')),
                ('points_to_improve', models.TextField(verbose_name='Pontos a Melhorar')),
                ('feedback_given', models.BooleanField(default=False, verbose_name='Feedback já foi passado?')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.teacherassignment', verbose_name='Aula Observada')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations_made', to=settings.AUTH_USER_MODEL, verbose_name='Coordenador')),
            ],
            options={
                'verbose_name': 'Observação de Sala',
                'verbose_name_plural': 'Observações de Sala',
            },
        ),
        migrations.CreateModel(
            name='MeetingMinute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título / Pauta')),
                ('date', models.DateField(verbose_name='Data da Reunião')),
                ('participants', models.TextField(verbose_name='Participantes')),
                ('content', models.TextField(verbose_name='Conteúdo / Decisões')),
                ('next_steps', models.TextField(blank=True, verbose_name='Próximos Passos / Tarefas')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ata de Reunião',
                'verbose_name_plural': 'Atas de Reunião',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Início da Semana')),
                ('end_date', models.DateField(verbose_name='Fim da Semana')),
                ('description', models.TextField(verbose_name='Resumo das Atividades')),
                ('pending_issues', models.TextField(blank=True, verbose_name='Pendências / Pontos de Atenção')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Relatório Semanal',
                'verbose_name_plural': 'Relatórios Semanais',
                'ordering': ['-start_date'],
            },
        ),
    ]
