# Generated by Django 5.2.8 on 2025-12-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classobservation',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Lido pelo Professor'),
        ),
    ]
