# Generated by Django 5.2.8 on 2025-12-19 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_attendance_justified_absencejustification'),
        ('coordination', '0002_classobservation_is_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data do Relatório')),
                ('subject', models.CharField(max_length=200, verbose_name='Assunto')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente de Aprovação'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Precisa de Ajustes')], default='PENDING', max_length=20)),
                ('visible_to_family', models.BooleanField(default=False, verbose_name='Disponível para os Pais')),
                ('coordinator_comment', models.TextField(blank=True, null=True, verbose_name='Comentário da Coordenação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='academic.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
