# Generated by Django 5.2.8 on 2026-02-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0003_studentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreport',
            name='report_type',
            field=models.CharField(choices=[('PEDAGOGICAL', 'Pedagógico/Acompanhamento'), ('DISCIPLINARY', 'Disciplinar/Ocorrência'), ('PRAISE', 'Elogio/Mérito'), ('MEDICAL', 'Saúde/Enfermaria')], default='PEDAGOGICAL', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='studentreport',
            name='severity_level',
            field=models.CharField(choices=[('LOW', 'Baixo/Informativo'), ('MEDIUM', 'Médio/Atenção'), ('CRITICAL', 'Crítico/Urgente')], default='LOW', max_length=10, verbose_name='Nível de Gravidade'),
        ),
    ]
